modLoader="javafml"
loaderVersion="[31,)"
issueTrackerURL="https://github.com/Tastac/DungeonsMod/issues"

[[mods]]
modId="${modId}"
version="${version}"
displayName="${name}"
logoFile="dungeonsmod.png"
authors="${author}"
description='''
'''

[[dependencies.dungeonsmod]]
    modId="forge"
    mandatory=true
    versionRange="[31,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.dungeonsmod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"
[[dependencies.coffeecolor]]
    modId="curios"
    mandatory=true
    versionRange="[FORGE-1.15.2-2,]"
    ordering="NONE"
    side="BOTH"
